% -------------------------------------------------------------------
%  Generated by MATLAB on 5-Apr-2023 14:18:23
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------

f = 110;
distance_corde_capteur = 0.00382;
freq_min = 80;
inv = -1; 

if inv < 0 % 2iem harmo
    f_1 = f/2;
    freq_min_1 = freq_min/2;

else % 1er harmo
    f_1 = f;
    freq_min_1 = freq_min;
end

Longueur = 0.44;

T_init = 77.527999999999992;

beta = 0.0032;

c = 88;

dt = 0.000125;

dx = 0.022;



masse = 0.004405;


mu = 0.010011363636363636;

n = 21;

p_actionneur = 16;

p_capteur = 5;

